---
dist: xenial
branches:
  only:
    - master
jobs:
  include:
    - name: Run Tests
      env: >
        VSPHERE_USER=nobody
        TF_IN_AUTOMATION=true
        VAULT_ADDR="https://127.0.0.1:8200"
        VSPHERE_PASSWORD=empty
install:
  - curl -sSfL -o /tmp/terraform.zip "https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip"
  - unzip /tmp/terraform.zip -d "$HOME/bin"
  - terraform --version
  - shellcheck --version
script:
  - "./tests/runtests.sh"
notifications:
  slack:
    on_success: always
    on_failure: always
    template:
      - "%{repository_slug} #%{build_number} (%{branch} - %{commit} - %{author})"
      - "Status: %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
    secure: D5grY0eJ9MCmMvQRQEtgLZyXSJZX/Q9atCJfEmZ/S6r9+Yka50Vmkl9RsU0eTlayvMVp+MTqiktXYA1A80FS3oBvFHCLe73YsqBVNIspckh4CeyXirkOFG9Ef0tMWDQkjo7AKvmj2p28t/mSSW2JGAs/fHsF1BqGtU9ZtUFfIPgMmirtK7/nTSYKSv/Hch95crF95J8lMbJeDBsWQKrIgk3yEoIuBWmFATbzYC+aR+g2qtWD76W8MMigqHjFvwHSS1ZRl+NniidfoRigh6XlLEs7ZRyPBK0T2EgzLTB0Qru29tyQvtQD5bqOTbOD3EXjxc1pULMbvNxS8BufJgBex3yoY4FdNE2+qT6AD6eagcpkmdSrc1M30wGBnffLXu8MPkV1jBiz5yg4qFu5sWtNqphUu92tt5/vmoRApw7jlLmASuwKP0hV1mriwC8gGP1uR2cbeNKlKOAGUW7sV+jvBcVF+pCAbzbTCzvnQ1chLMctMkz5Zk4BtX3EJ9z+Q7+Fg0zpfpxKOjnKGn1tWHRIxZbV3GCLruJF7O0q/WH4I4kN4stG4BexKou74Sbvc5a6SdEWbtybrIi1tUvpZYu9mkaKZvCW9/mWi+OkxA7FOg2creadYNiKG2reziYGBwPYq0kbiSP6XZMDuF2HaZ4c9zfY7hV9W/d/B1AzUQSpwos=
